version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis_container
    hostname: redis
    ports:
      - "6379:6379"

  springboot:
    image: ${DOCKER_USERNAME}/pm-be:latest
    container_name: springboot_container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env